# github.com/flipped-aurora/md-server/server Global Configuration

# jwt configuration
jwt:
  signing-key: 'xhuiteam'
  expires-time: 604800
  buffer-time: 86400
  issuer: 'xhuiteam'
# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[github.com/kaij_yin/md-server/server]'
  director: 'log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# redis configuration
redis:
  db: 0
  addr: '127.0.0.1:6379'
  password: ''

# system configuration
system:
  env: 'public'
  ip-addr: '127.0.0.1'
  port: 8888
  db-type: 'mysql'



# mysql connect configuration
mysql:
  path: ''
  config: ''
  db-name: ''
  username: ''
  password: ''
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false









